### ISSUE TITLE
Incorrect start and end dates in google calendar

### ISSUE THREAD

**Issue by BigBlockStudios** [pdincubus/JSONDerulo#24]
Small issue with the google calendar dates: 

'eventEnd' => strtotime($event->start->dateTime),
'eventStart' => strtotime($event->end->dateTime),

a pretty obvious fix, just FYI for your next update.

**Comment by andrewmfraser** [comment]
eventEnd isn't implemented at the moment I'll sort that, but I don't see any issue with eventStart. If you look at https://github.com/pdincubus/JSONDerulo/blob/master/v2/snippet.JSONDerulo.php#L390-399 you can see that it fetches the date rather than the dateTime if it's an all day event otherwise for an all day event no date will be returned.

We'll have to do the same with eventEnd, passing either date or dateTime depending on the type of event.

However at the moment #23 seems to be more of a problem, all the times are 1 hour out, are you seeing the same thing?

**Comment by andrewmfraser** [comment]
I see now you're using an older version. Once we sort #23 I'm sure @pdincubus will rebuild the transport package and release an update.

**Comment by BigBlockStudios** [comment]
I just downloaded what was in the repo.  and switched the date placeholders around. it seems to work enough for me for right now.
