### ISSUE TITLE
PHP 7 issue: 'continue' not in the 'loop' or 'switch' context

### ISSUE THREAD

**Issue by raffy99** [pdincubus/JSONDerulo#30]
on line 225 and line 1242 a "continue" is used in loop context. replacing it with a "return" solved it in my first impression

**Comment by pdincubus** [comment]
Fixed in commit  https://github.com/pdincubus/JSONDerulo/commit/6c2bd3975696748c3dc9374705da9ac2a76d6de9

New transport package [here](https://github.com/pdincubus/JSONDerulo/blob/master/v2/Transport%20Packages/jsonderulo-2.5.5-pl.transport.zip)

MODX extras repo to be updated when they fix it, seemingly I can't upload a new package version at the moment.
