### ISSUE TITLE
output modifiers such as "default" do not work on V2 of JSONDerulo

### ISSUE THREAD

**Issue by pmacswebteam** [pdincubus/JSONDerulo#38]
I am trying to add default text for when a Google Calendar has no upcoming events, however, the following is being ignored:

[[JSONDerulo:isempty=`<li>There are no events scheduled at this time.</li>` ?
  &feed=`googlecalendar`
  &tpl=`googleCalendar-tpl`
  &limit=`5`
  ...
  ..
  .
  ]]

**Comment by pdincubus** [comment]
Hi there,

The default output from some/most of the feeds is to return a 'No events' or 'No posts' message if they're empty. I wrote it that was because that's what I needed at the time. You can see the calendar one in the chunk https://github.com/pdincubus/JSONDerulo/blob/master/v2/Chunks/jd.googleCalendar.html#L2

If you need a quick fix for the calendar, you could just edit this part of the snippet: https://github.com/pdincubus/JSONDerulo/blob/master/v2/snippet.JSONDerulo.php#L377

To output nothing, as in remove the else part altogether and just close the if statement. That should then return as empty/null/whatever it is that MODX actually thinks nothing is!

**Comment by pmacswebteam** [comment]
Thanks for your reply! What I ended up doing was the following within the template:

```
[[+title:ne=`No events.`:then=`<a href="[[+link]]" target="_blank">[[+title]]</a><br>`:else=`There are no events scheduled at this time.`]]
```
